name = "quake-service"
main = "_worker.js"
compatibility_date = "2024-01-01"

[vars]
MIN_MAGNITUDE = 3
MAX_DEPTH_KM = 300
QUAKE_CACHE_TTL_DAYS = 2
GEONET_POLLING_INTERVAL_SECONDS = 45
FULL_REFRESH_INTERVAL_MINUTES = 45
RECENT_QUAKE_POLL_TIME_MINUTES = 20
QUAKE_SEARCH_TIME_MINUTES = 10

[[durable_objects.bindings]]
name = "QUAKE_SERVICE"
class_name = "QuakeService"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["QuakeService"]

[triggers]
crons = ["*/2 * * * *"]
